

INSERT INTO USUARIO (ID, USER_NAME, PASWORD) VALUES (1, 'kaksuma', 'clave10');
INSERT INTO USUARIO (ID, USER_NAME, PASWORD) VALUES (2, 'angee', 'clave10');
INSERT INTO USUARIO (ID, USER_NAME, PASWORD) VALUES (3, 'backtome', 'clave10');
INSERT INTO USUARIO (ID, USER_NAME, PASWORD) VALUES (4, 'pollo', 'clave10');